# Estas são plataformas de modelo de financiamento suportadas

github: # Substitua por até 4 nomes de usuários habilitados para patrocinadores do GitHub, por exemplo, [user1, user2]
patreon: # Substitua por um único nome de usuário do Patreon
open_collective: # Substitua por um único nome de usuário do Open Collective
ko_fi: # Substitua por um único nome de usuário Ko-fi
tidelift: # Substitua por um único Tidelift platform-name/package-name, por exemplo, npm/babel
community_bridge: # Substitua por um único nome de projeto do Community Bridge, por exemplo, cloud-foundry
liberapay: # Substitua por um único nome de usuário Liberapay
issuehunt: # Substitua por um único nome de usuário IssueHunt
otechie: # Substitua por um único nome de usuário Otechie
custom: ['https://saweria.co/Nurutomo'] # Substitua por até 4 URLs de patrocínio personalizados, por exemplo, ['link1', 'link2']
