# Este fluxo de trabalho fará uma instalação limpa das dependências do node, compilará o código-fonte e executará testes em diferentes versões do node
# Para obter mais informações, consulte: https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x]
        # Veja o cronograma de lançamento do Node.js suportado em  https://nodejs.org/pt-br/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # Porque estamos apenas verificando SyntaxError
    # - execute: npm i
    - run: npm test
